language: ruby
#bundler_args: --without development

env:
  - CI=true
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - Gemfile
before_script:
  - sudo ./spec/support/setup-test.sh
env:
  - CHEF_VERSION=10.28.0
  - CHEF_VERSION=11.6.0
